version: '3.8'

services:
  postgres:
    container_name: football-game-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_USERNAME}
      - POSTGRES_DB=${DB_USERNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: