apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque

data:
  # Use base64 to encode the password. You can generate this with `echo -n 'yourpassword' | base64`
  postgres-user: YWRtaW4=
  postgres-password: YWRtaW4=
  postgres-db: Zm9vdGJhbGwtZ2FtZQ==